CREATE DATABASE $(MSSQL_DB);
GO
USE $(MSSQL_DB);
GO
CREATE LOGIN $(MSSQL_USER) WITH PASSWORD = '$(MSSQL_PASSWORD)';
GO
CREATE USER $(MSSQL_USER) FOR LOGIN $(MSSQL_USER);
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [$(MSSQL_USER)];
GO
CREATE TABLE access_denied (id int);
GO
CREATE LOGIN unprivileged WITH PASSWORD = 'unprivileged1!';
GO
CREATE USER unprivileged FOR LOGIN unprivileged;
GO
